CREATE TABLE ALL_SEQUENCES
(
SEQUENCE_OWNER VARCHAR2(30) NOT NULL  ,
SEQUENCE_NAME VARCHAR2(30)  NOT NULL  ,
MIN_VALUE               NUMBER       ,
MAX_VALUE               NUMBER       ,
INCREMENT_BY NUMBER  NOT NULL        ,
CYCLE_FLAG              VARCHAR2(1)  ,
ORDER_FLAG              VARCHAR2(1)  ,
CACHE_SIZE   NUMBER  NOT NULL        ,
LAST_NUMBER  NUMBER  NOT NULL
);

CREATE TABLE ALL_SYNONYMS
(
OWNER              VARCHAR2(30),
SYNONYM_NAME       VARCHAR2(30),
TABLE_OWNER        VARCHAR2(30),
TABLE_NAME         VARCHAR2(30),
DB_LINK            VARCHAR2(128)
);

CREATE TABLE example
(
    id NUMBER(19,0) PRIMARY KEY NOT NULL,
    create_date TIMESTAMP,
    change_date TIMESTAMP,
    value VARCHAR(255)
);

CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;